### ISSUE TITLE
copy oo2core_8_win64.dll frome Warframe,but it couldn’t work

### ISSUE THREAD

**Issue by Fitmtfk** [mhvuze/WorldChunkTool#12]
it throw the error HRESULT:0x8007000B

**Comment by dannylin0711** [comment]
Same here, error HRESULT: 0x8007000B

**Comment by mhvuze** [comment]
Interesting, I’ll look into it before official release. It works fine with the Jedi version for me.

**Comment by mhvuze** [comment]
I just confirmed it works fine with the Warframe DLL. You likely tried to use a 32bit version of the tool with the DLL (which is 64bit). Also, you shouldn't use the tool at this point in time anyway, as it won't properly unpack most files. The release version won't have this self-inflicted problem.

**Comment by sekaiwish** [comment]
This issue is still present in version 1.2.2 using the 64bit version of oo2core8.

```
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at WorldChunkTool.Utils.OodleLZ_Decompress(Byte[] buffer, Int64 bufferSize, Byte[] outputBuffer, Int64 outputBufferSize, UInt32 a, UInt32 b, UInt64 c, UInt32 d, UInt32 e, UInt32 f, UInt32 g, UInt32 h, UInt32 i, UInt32 threadModule)
   at WorldChunkTool.Utils.Decompress(Byte[] buffer, Int32 size, Int32 uncompressedSize)
   at WorldChunkTool.ChunkOTF.getDecompressedChunk(Int64 offset, Int64 size, BinaryReader reader, Boolean FlagBaseGame, Int32 chunkNum)
   at WorldChunkTool.ChunkOTF.AnalyzeChunk(String FileInput, List`1 inputFileList, Boolean FlagBaseGame)
   at WorldChunkTool.Program.ProcessFile(String FileInput)
   at WorldChunkTool.Program.Main(String[] args)
```

**Comment by sekaiwish** [comment]
After a reboot, some additional faffing around and copying it from the Warframe tools again, it did start working and extracted from the chunk successfully. I'm not sure what exactly made this happen but it works now.
